name: CI

on:
  push:
    branches: [staging, trying]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.66.0
          default: true
          profile: minimal
          components: rustfmt, clippy

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0
          profile: minimal

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - name: cargo fmt
        run: cargo fmt -- --check

      - name: clippy and tests
        run: ./test.sh

      - name: MSRV check
        run: cargo +1.60.0 check --all --all-targets --all-features
