name: Publish

on:
  push:
    tags: v.+
  workflow_dispatch:
    inputs:
      dry_run:
        description: Dry run
        type: boolean
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: ${{ inputs.dry_run }}
